### ISSUE TITLE
Yarn command does nothing

### ISSUE THREAD

**Issue by TomWor** [Calinou/godot-asset-library-laravel#63]
Environment: MacOSX 10.14

Running the 'yarn' command like mentioned in the readme does not install any dependencies:

```
godot-asset-library-laravel on master [!?] via ⬢ v9.11.2 via 🐘 v7.1.32 took 1m 18s
➜ yarn
yarn

Commands:
  init   scaffold a new yarn site
  new    create new content
  build  build your site
  clean  cleans destination folder
  serve  serve your site with http-server
  watch  build, serve, and watch for file changes

Options:
  --incremental  only build files that have changed    [boolean] [default: true]
  --verbose      log out additional log information                    [boolean]
  --version, -v  installed version                                     [boolean]
  --help         Show help                                             [boolean]


```

'yarn watch' results in

```
godot-asset-library-laravel on  master [!?] via ⬢ v9.11.2 via 🐘 v7.1.32 took 2s
➜ yarn watch
yarn

/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/lib/config/index.js:156
        throw new Error('_config.yml requires a \'path\' value.');
        ^

Error: _config.yml requires a 'path' value.
    at Config.update (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/lib/config/index.js:156:15)
    at Config.loadLocal (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/lib/config/index.js:143:12)
    at Config.setRoot (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/lib/config/index.js:127:14)
    at Function.create (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/lib/config/index.js:227:14)
    at exports.default (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/bin/serve.js:8:33)
    at exports.default (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/bin/watch.js:9:23)
    at Object.<anonymous> (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/bin/index.js:93:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/tomwor/.nvm/versions/node/v9.11.2/lib/node_modules/yarn-cli/node_modules/yarnjs/dist/bin/yarn.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
```

yarn is at version '1.4.0'

**Comment by Calinou** [comment]
Did the Yarn developers recently remove the implicit `yarn` = `yarn install` alias? I'll tweak the README to account for this.

**Comment by TomWor** [comment]
You were right, works now!
